#!/usr/bin/env python3
"""Generates docs/generated/component-inventory.md from plugin contents.

Hand-editing is forbidden; `--check` (run by check.py) fails on drift.
"""
import json
import sys

import harness_lib as hl

HEADER = ("<!-- GENERATED by plugin/scripts/gen_inventory.py — do not hand-edit. "
          "Regenerate: python3 plugin/scripts/gen_inventory.py -->")


def build(plugin):
    rows = []
    for md in sorted((plugin / "skills").glob("*/SKILL.md")):
        fm = hl.read_frontmatter(md) or {}
        rows.append(("skill", md.parent.name, fm.get("description", "")[:100],
                     f"plugin/skills/{md.parent.name}/SKILL.md"))
    for md in sorted((plugin / "agents").glob("*.md")):
        fm = hl.read_frontmatter(md) or {}
        rows.append(("agent", md.stem, fm.get("description", "")[:100],
                     f"plugin/agents/{md.name}"))
    hooks = plugin / "hooks" / "hooks.json"
    if hooks.exists():
        cfg = json.loads(hooks.read_text(encoding="utf-8"))
        for event, entries in sorted(cfg.get("hooks", {}).items()):
            for entry in entries:
                for h in entry.get("hooks", []):
                    cmd = h.get("command", "")
                    script = cmd.rsplit("/", 1)[-1].split('"')[0].split(" ")[0]
                    rows.append(("hook", event, f"runs `{script}`", "plugin/hooks/hooks.json"))
    lines = [HEADER, "", "# Component inventory", "",
             "| Type | Name | Description / wiring | Source |", "|---|---|---|---|"]
    lines += [f"| {t} | {n} | {d} | {s} |" for t, n, d, s in rows]
    return "\n".join(lines) + "\n"


def out_path(root):
    return root / "docs" / "generated" / "component-inventory.md"


def check(plugin, out):
    return out.exists() and out.read_text(encoding="utf-8") == build(plugin)


def main():
    root = hl.repo_root()
    plugin = hl.plugin_root()
    out = out_path(root)
    if "--check" in sys.argv:
        if not check(plugin, out):
            print(f"FAIL GEN docs/generated/component-inventory.md: stale or hand-edited. "
                  f"FIX: run `python3 plugin/scripts/gen_inventory.py` and commit the result.")
            sys.exit(1)
        print("gen_inventory: OK")
        return
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build(plugin), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
